org.gradle.jvmargs=-Xmx4g -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true

android.useAndroidX=true
android.nonTransitiveRClass=true

kotlin.code.style=official

# Turns on Metro's experimental Circuit codegen, which generates Presenter.Factory and
# Ui.Factory multibindings from @CircuitInject. No separate Circuit KSP processor needed.
metro.enableCircuitCodegen=true
metro.generateContributionProviders = true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
